### PR TITLE
support specifying room

### PR DESCRIPTION
**Pull request by notok**
Thank you for great script!

I'm using this script to make scheduled announcements to my team,
and I don't wanna show the message before they're sent.
(i.e. I want to hide message like `hubot schedule add "0 10 * * 1-5" Don't forget to...` from team members.)

So, I tried to implement sending messages to specified room. Please check this out.

### CODE REVIEW

**Comment by matsukaz** [comment]
Thanks for your pr !
It sounds really nice and I'm willing to merge it.
But I have few points I want to consider.
1. `schedule list` is now showing all channel schedules. This used to show only messages that was scheduled to the current channel.
2. maybe we should add `schedule del #channel` also in case of any mistype or re-scheduling. But this might cause some trouble because anyone could remove schedule from any other channels. what do you think about this?

**Comment by notok** [comment]
Thanks for your comment.

For 1st point, I added option for `schedule list`. Please check it.
- `schedule list`: show schedule for current room
- `schedule list all`: show schedule for all rooms
- `schedule list #<room>`: show schedule for specified room

For 2nd point, unfortunately, I have no good idea for now.
I think the problem is that anyone can delete schedule, and others cannot notice that.
I need a bit more time to consider. I'll re-comment by this weekend.

**Comment by matsukaz** [comment]
`schedule list` looks perfect, thank you! :)

For the 2nd point, I don't have any idea either...
How about adding some configurations like `HUBOT_SCHEDULE_DENY_EXTERNAL_CONTROL` and set `false` as default ?
If this is set as `false`, anyone can add, remove or list other rooms schedules.
If set as `true`, noone can add, remove, or list other rooms schedules.
Most people are willing to use this feature, so setting `false` make sense.

If you have any other ideas or any difficulties, plz let me know :)

**Comment by notok** [comment]
Thanks for your comment!

I also think it's good way to add an option. I'll try to implement.

**Comment by notok** [comment]
Sorry for late response.

I added `HUBOT_SCHEDULE_DENY_EXTERNAL_CONTROL` option.
I choose the value `1` for the option from other options. 

Please check it.

**Comment by matsukaz** [comment]
Thanks for adding my requests.
It looks perfect so I'm gonna merge into master branch :)

I'm going to add some more features and try refactoring before bump to v0.5.0, so plz wait a moment.

**Comment by notok** [comment]
Thank you too for your help and accepting my PR!

I have one more feature request. So, I'm going to raise an issue about it.
Please have a look on it.

**Pull request merged**
